import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Kursy
  const analityka = await prisma.course.upsert({
    where: { slug: 'analityka-danych' },
    update: {},
    create: {
      slug: 'analityka-danych',
      title: 'Analityka Danych',
      description: 'Kompleksowy kurs analityki danych: SQL, Python, pandas, wizualizacje.',
      priceGrosze: 24900,
    },
  });

  const ai = await prisma.course.upsert({
    where: { slug: 'ai-machine-learning' },
    update: {},
    create: {
      slug: 'ai-machine-learning',
      title: 'AI i Machine Learning',
      description: 'Praktyczny kurs AI/ML: sieci neuronowe, scikit-learn, wdrożenia.',
      priceGrosze: 34900,
    },
  });

  console.log('✅ Courses created:', analityka.slug, ai.slug);

  // Admin user
  const admin = await prisma.user.upsert({
    where: { email: 'admin@neurova.pl' },
    update: {},
    create: {
      email: 'admin@neurova.pl',
      name: 'Admin Neurova',
      role: 'ADMIN',
      emailVerified: new Date(),
    },
  });
  console.log('✅ Admin user:', admin.email);

  // Test user — do testów manualnych (staging)
  const testUser = await prisma.user.upsert({
    where: { email: 'test@example.com' },
    update: { emailVerified: new Date() },
    create: {
      email: 'test@example.com',
      name: 'Test User',
      role: 'USER',
      emailVerified: new Date(),
      acceptedTermsVersion: '1.0',
      marketingConsent: false,
    },
  });
  console.log('✅ Test user:', testUser.email);

  // Test user — płatności SUCCESS dla obu kursów (dostęp do treści)
  await prisma.payment.upsert({
    where: { p24SessionId: 'seed_test_analityka' },
    update: { status: 'SUCCESS' },
    create: {
      userId: testUser.id,
      courseId: analityka.id,
      p24SessionId: 'seed_test_analityka',
      expectedAmountGrosze: 24900,
      status: 'SUCCESS',
    },
  });
  await prisma.payment.upsert({
    where: { p24SessionId: 'seed_test_ai' },
    update: { status: 'SUCCESS' },
    create: {
      userId: testUser.id,
      courseId: ai.id,
      p24SessionId: 'seed_test_ai',
      expectedAmountGrosze: 34900,
      status: 'SUCCESS',
    },
  });
  console.log('✅ Test user payments created (full course access)');

  // Pytania egzaminacyjne — Analityka Danych (60 pytań)
  const adQuestions = [
    { text: 'Co zwraca zapytanie SELECT COUNT(*) FROM tabela WHERE warunek = FALSE?', optionA: 'Liczbę wierszy spełniających warunek', optionB: 'Liczbę wierszy niespełniających warunku', optionC: '0', optionD: 'Błąd składni', correctOption: 'B', explanation: 'COUNT(*) liczy wiersze spełniające klauzulę WHERE, czyli te gdzie warunek = FALSE.' },
    { text: 'Które polecenie SQL służy do usunięcia całej tabeli wraz z jej strukturą?', optionA: 'DELETE TABLE', optionB: 'TRUNCATE TABLE', optionC: 'DROP TABLE', optionD: 'REMOVE TABLE', correctOption: 'C', explanation: 'DROP TABLE usuwa tabelę i jej strukturę. TRUNCATE usuwa tylko dane, DELETE usuwa wiersze.' },
    { text: 'Co robi GROUP BY w zapytaniu SQL?', optionA: 'Sortuje wyniki', optionB: 'Grupuje wiersze o identycznych wartościach w podane kolumny', optionC: 'Filtruje wiersze', optionD: 'Łączy tabele', correctOption: 'B', explanation: 'GROUP BY agreguje wiersze z tymi samymi wartościami w podanych kolumnach.' },
    { text: 'Która funkcja okna SQL oblicza numer wiersza w ramach partycji?', optionA: 'RANK()', optionB: 'ROW_NUMBER()', optionC: 'NTILE()', optionD: 'DENSE_RANK()', correctOption: 'B', explanation: 'ROW_NUMBER() przypisuje unikalny numer wierszom w ramach partycji.' },
    { text: 'Czym różni się INNER JOIN od LEFT JOIN?', optionA: 'INNER JOIN zwraca tylko pasujące wiersze; LEFT JOIN zwraca wszystkie z lewej tabeli', optionB: 'Nie ma różnicy', optionC: 'LEFT JOIN jest szybszy', optionD: 'INNER JOIN zwraca wszystkie wiersze', correctOption: 'A', explanation: 'INNER JOIN = część wspólna. LEFT JOIN = wszystkie wiersze z lewej + pasujące z prawej (NULL gdy brak).' },
    { text: 'Jaka biblioteka Python służy do analizy danych tabelarycznych?', optionA: 'numpy', optionB: 'pandas', optionC: 'matplotlib', optionD: 'scipy', correctOption: 'B', explanation: 'pandas to główna biblioteka do analizy danych tabelarycznych w Python (DataFrame, Series).' },
    { text: 'Co robi metoda df.describe() w pandas?', optionA: 'Wyświetla strukturę DataFrame', optionB: 'Zwraca statystyki opisowe kolumn numerycznych', optionC: 'Usuwa braki danych', optionD: 'Sortuje DataFrame', correctOption: 'B', explanation: 'describe() zwraca count, mean, std, min, max, percentyle dla kolumn numerycznych.' },
    { text: 'Jak usunąć wiersze z brakami w pandas?', optionA: 'df.remove_na()', optionB: 'df.drop_missing()', optionC: 'df.dropna()', optionD: 'df.fillna(0)', correctOption: 'C', explanation: 'dropna() usuwa wiersze (lub kolumny) zawierające wartości NaN.' },
    { text: 'Co to jest ETL?', optionA: 'Extract, Transform, Load', optionB: 'Evaluate, Test, Launch', optionC: 'Export, Transfer, Link', optionD: 'Edit, Track, Log', correctOption: 'A', explanation: 'ETL = Extract (ekstrakcja danych), Transform (transformacja), Load (załadowanie do docelowego systemu).' },
    { text: 'Jaki jest cel normalizacji danych?', optionA: 'Przyspieszenie zapytań', optionB: 'Eliminacja redundancji i anomalii modyfikacji', optionC: 'Szyfrowanie danych', optionD: 'Tworzenie kopii zapasowych', correctOption: 'B', explanation: 'Normalizacja redukuje redundancję i chroni przed anomaliami INSERT/UPDATE/DELETE.' },
    { text: 'Jaka jest różnica między HAVING a WHERE w SQL?', optionA: 'HAVING filtruje przed grupowaniem, WHERE po', optionB: 'WHERE filtruje przed grupowaniem, HAVING filtruje grupy po GROUP BY', optionC: 'Są identyczne', optionD: 'HAVING jest szybsze', correctOption: 'B', explanation: 'WHERE filtruje wiersze przed agregacją, HAVING filtruje wyniki po GROUP BY.' },
    { text: 'Co oznacza kardynalność kolumny?', optionA: 'Liczbę wierszy w tabeli', optionB: 'Liczbę unikalnych wartości w kolumnie', optionC: 'Rozmiar kolumny w bajtach', optionD: 'Typ danych kolumny', correctOption: 'B', explanation: 'Kardynalność = liczba unikalnych (distinct) wartości w kolumnie. Wysoka kardynalność = dobry kandydat na indeks.' },
    { text: 'Czym jest outlier (wartość odstająca)?', optionA: 'Brakującą wartością', optionB: 'Wartością znacznie odbiegającą od pozostałych obserwacji', optionC: 'Duplikatem wiersza', optionD: 'Wartością zerową', correctOption: 'B', explanation: 'Outlier to obserwacja oddalona o wiele odchyleń standardowych od średniej lub mediany.' },
    { text: 'Który typ wykresu najlepiej pokazuje rozkład zmiennej numerycznej?', optionA: 'Wykres kołowy', optionB: 'Wykres słupkowy', optionC: 'Histogram', optionD: 'Wykres liniowy', correctOption: 'C', explanation: 'Histogram dzieli zakres wartości na przedziały i pokazuje częstość występowania — idealny dla rozkładu.' },
    { text: 'Co to jest mediana?', optionA: 'Średnia arytmetyczna', optionB: 'Najczęstsza wartość', optionC: 'Środkowa wartość po posortowaniu', optionD: 'Różnica między max a min', correctOption: 'C', explanation: 'Mediana = wartość środkowa zbioru posortowanego. Odporna na outlier\'y w przeciwieństwie do średniej.' },
    { text: 'Jaka metoda pandas łączy DataFrame\'y poziomo (po kolumnach)?', optionA: 'pd.concat(axis=0)', optionB: 'pd.concat(axis=1)', optionC: 'df.merge()', optionD: 'df.append()', correctOption: 'B', explanation: 'pd.concat(axis=1) łączy DataFrame\'y poziomo (dodaje kolumny). axis=0 łączy pionowo (dodaje wiersze).' },
    { text: 'Co to jest pivot table?', optionA: 'Tabela z kluczem obcym', optionB: 'Tabela przestawna agregująca dane według wielu wymiarów', optionC: 'Indeks bazy danych', optionD: 'Widok SQL', correctOption: 'B', explanation: 'Tabela przestawna (pivot) agreguje dane — wartości z jednej kolumny stają się nagłówkami nowych kolumn.' },
    { text: 'Jaka funkcja agregująca zwraca wartość w określonym percentylu?', optionA: 'AVG()', optionB: 'PERCENTILE_CONT()', optionC: 'MEDIAN()', optionD: 'MODE()', correctOption: 'B', explanation: 'PERCENTILE_CONT() to funkcja okna SQL obliczająca interpolowany percentyl (np. PERCENTILE_CONT(0.5) = mediana).' },
    { text: 'Czym jest data warehouse?', optionA: 'Bazą danych OLTP do transakcji', optionB: 'Centralnym repozytorium danych historycznych zoptymalizowanym pod analitykę (OLAP)', optionC: 'Serwerem plików', optionD: 'Narzędziem ETL', correctOption: 'B', explanation: 'Data warehouse (hurtownia danych) przechowuje duże ilości historycznych danych z wielu źródeł do analizy.' },
    { text: 'Co to jest schema star w data warehouse?', optionA: 'Schemat z wieloma tabelami faktów', optionB: 'Schemat z centralną tabelą faktów otoczoną tabelami wymiarów', optionC: 'Schemat znormalizowany do 3NF', optionD: 'Schemat replikacji', correctOption: 'B', explanation: 'Schemat gwiazdy: centralna tabela faktów (miary) + otaczające tabele wymiarów (kontekst). Prosta do zapytań.' },
    { text: 'Które z poniższych jest miarą rozproszenia danych?', optionA: 'Średnia', optionB: 'Mediana', optionC: 'Odchylenie standardowe', optionD: 'Moda', correctOption: 'C', explanation: 'Odchylenie standardowe (std) mierzy rozproszenie wartości wokół średniej. Miary: std, wariancja, rozstęp.' },
    { text: 'Co robi df.groupby(\'kolumna\')[\'wartość\'].sum() w pandas?', optionA: 'Sortuje po kolumnie', optionB: 'Grupuje po kolumnie i sumuje wartości w każdej grupie', optionC: 'Usuwa duplikaty', optionD: 'Filtruje DataFrame', correctOption: 'B', explanation: 'groupby() + agregacja to odpowiednik GROUP BY w SQL. Tworzy grupy i stosuje funkcję agregującą.' },
    { text: 'Czym jest korelacja Pearsona?', optionA: 'Miarą centralną', optionB: 'Miarą liniowej zależności między dwiema zmiennymi (-1 do 1)', optionC: 'Testem normalności', optionD: 'Miarą rozproszenia', correctOption: 'B', explanation: 'Korelacja Pearsona: 1 = pełna zależność dodatnia, 0 = brak, -1 = pełna zależność ujemna.' },
    { text: 'Jak w SQL wybrać unikalne wartości z kolumny?', optionA: 'SELECT UNIQUE kolumna FROM tabela', optionB: 'SELECT DISTINCT kolumna FROM tabela', optionC: 'SELECT kolumna HAVING COUNT(*) = 1 FROM tabela', optionD: 'SELECT kolumna FROM tabela GROUP BY kolumna HAVING COUNT(*) > 1', correctOption: 'B', explanation: 'DISTINCT eliminuje duplikaty z wyników zapytania.' },
    { text: 'Co to jest CTE (Common Table Expression)?', optionA: 'Widok tymczasowy definiowany w ramach zapytania za pomocą WITH', optionB: 'Typ indeksu', optionC: 'Procedura składowana', optionD: 'Trigger bazodanowy', correctOption: 'A', explanation: 'CTE (WITH name AS (...)) to tymczasowy zbiór wyników używany w kolejnym zapytaniu. Poprawia czytelność.' },
    { text: 'Które narzędzie BI jest bezpłatne i open-source?', optionA: 'Tableau', optionB: 'Power BI Pro', optionC: 'Metabase', optionD: 'Qlik Sense', correctOption: 'C', explanation: 'Metabase to popularne bezpłatne narzędzie BI open-source. Tableau i Power BI Pro są płatne.' },
    { text: 'Co robi COALESCE(a, b, c) w SQL?', optionA: 'Zwraca sumę a+b+c', optionB: 'Zwraca pierwszą wartość nie-NULL z listy argumentów', optionC: 'Łączy ciągi tekstowe', optionD: 'Zwraca największą wartość', correctOption: 'B', explanation: 'COALESCE() zwraca pierwszy argument nie-NULL. Użyteczny do obsługi braków danych.' },
    { text: 'Jaki jest cel indeksu w bazie danych?', optionA: 'Zmniejszenie rozmiaru bazy', optionB: 'Przyspieszenie wyszukiwania danych kosztem miejsca i czasu zapisu', optionC: 'Szyfrowanie danych', optionD: 'Replikacja danych', correctOption: 'B', explanation: 'Indeks to struktura B-tree przyspieszająca SELECT, ale spowalniająca INSERT/UPDATE/DELETE.' },
    { text: 'Co to jest ACID w kontekście baz danych?', optionA: 'Atomicity, Consistency, Isolation, Durability', optionB: 'Accuracy, Completeness, Integrity, Data', optionC: 'Automatic, Concurrent, Indexed, Distributed', optionD: 'Access, Control, Identity, Directory', correctOption: 'A', explanation: 'ACID gwarantuje niezawodność transakcji: Atomowość, Spójność, Izolację i Trwałość.' },
    { text: 'Która z metod obsługi braków danych (NaN) jest ryzykowna?', optionA: 'Usunięcie wierszy z NaN (dropna)', optionB: 'Imputacja medianą', optionC: 'Usunięcie kolumn z >80% NaN', optionD: 'Zastąpienie wartością 0 bez analizy', correctOption: 'D', explanation: 'Zastąpienie 0 bez analizy może wprowadzić błąd. Np. 0 przychodu zamiast braku danych zniekształca analizę.' },
    { text: 'Co to jest data lake?', optionA: 'Baza relacyjna', optionB: 'Repozytorium danych surowych w oryginalnych formatach (structured + unstructured)', optionC: 'Narzędzie wizualizacji', optionD: 'Protokół przesyłu danych', correctOption: 'B', explanation: 'Data lake przechowuje dane surowe w oryginalnych formatach, w przeciwieństwie do data warehouse ze schematem.' },
    { text: 'Jaki jest cel funkcji RANK() w SQL?', optionA: 'Przypisanie unikalnych numerów bez przerw', optionB: 'Przypisanie rang z przerwami przy remisach (1,1,3)', optionC: 'Podział na kwantyle', optionD: 'Obliczenie wartości kumulatywnej', correctOption: 'B', explanation: 'RANK() przy remisach pomija kolejne numery (1,1,3). DENSE_RANK() nie pomija (1,1,2).' },
    { text: 'Co oznacza "grain" (ziarno) tabeli faktów?', optionA: 'Liczbę kolumn', optionB: 'Najniższy poziom szczegółowości pojedynczego wiersza', optionC: 'Klucz główny tabeli', optionD: 'Indeks tabeli', correctOption: 'B', explanation: 'Grain definiuje co reprezentuje jeden wiersz w tabeli faktów (np. jeden wiersz = jedna transakcja).' },
    { text: 'Jak obliczyć sumę kumulatywną w SQL?', optionA: 'SUM(kolumna) OVER (ORDER BY data)', optionB: 'SUM(kolumna) GROUP BY data', optionC: 'CUMSUM(kolumna)', optionD: 'RUNNING_TOTAL(kolumna)', correctOption: 'A', explanation: 'Funkcja okna SUM() OVER (ORDER BY ...) tworzy sumę kumulatywną (running total).' },
    { text: 'Czym jest p-value w analizie statystycznej?', optionA: 'Prawdopodobieństwem, że hipoteza zerowa jest prawdziwa', optionB: 'Prawdopodobieństwem uzyskania wyników co najmniej tak ekstremalnych jak obserwowane, zakładając H0', optionC: 'Współczynnikiem korelacji', optionD: 'Rozmiarem próby', correctOption: 'B', explanation: 'p-value < 0.05 sugeruje odrzucenie H0. To prawdopodobieństwo wyniku, nie prawdopodobieństwo H0.' },
    { text: 'Co robi df.pivot_table(values=\'v\', index=\'i\', columns=\'c\', aggfunc=\'sum\')?', optionA: 'Sortuje DataFrame', optionB: 'Tworzy tabelę przestawną sumując wartości v dla każdej kombinacji i i c', optionC: 'Łączy DataFrame\'y', optionD: 'Transpozycja macierzy', correctOption: 'B', explanation: 'pivot_table() to odpowiednik tabeli przestawnej Excela — agreguje dane względem dwóch wymiarów.' },
    { text: 'Jaka jest różnica między szerokimi (wide) a długimi (long) formatami danych?', optionA: 'Brak różnicy', optionB: 'Wide: każda zmienna w osobnej kolumnie; Long: wiersze dla każdej obserwacji zmiennej', optionC: 'Wide ma więcej wierszy', optionD: 'Long jest szybszy do przetwarzania', correctOption: 'B', explanation: 'Tidy data (long format) = jedna obserwacja na wiersz. Wide format = jedna jednostka na wiersz, wiele kolumn.' },
    { text: 'Co to jest A/B test?', optionA: 'Metoda ML do klasyfikacji', optionB: 'Eksperyment porównujący dwie wersje (kontrolną A i wariantową B) na grupach użytkowników', optionC: 'Algorytm sortowania', optionD: 'Typ zapytania SQL', correctOption: 'B', explanation: 'A/B test to kontrolowany eksperyment do testowania hipotezy o efektywności zmiany (np. nowy przycisk).' },
    { text: 'Jaki format pliku jest najbardziej efektywny dla dużych danych analitycznych?', optionA: 'CSV', optionB: 'JSON', optionC: 'Parquet', optionD: 'XML', correctOption: 'C', explanation: 'Parquet to kolumnowy format binarny z kompresją — znacznie szybszy i mniejszy niż CSV/JSON dla analityki.' },
    { text: 'Co to jest SLA (Service Level Agreement) w kontekście danych?', optionA: 'Protokół szyfrowania', optionB: 'Umowa definiująca gwarantowany czas i jakość dostarczania danych (np. pipeline gotowy do 6:00)', optionC: 'Algorytm ML', optionD: 'Typ indeksu', correctOption: 'B', explanation: 'SLA dla pipeline\'ów danych definiuje oczekiwany czas dostarczenia, jakość i dostępność danych.' },
    { text: 'Jaka jest różnica między DIM a FACT tabelami?', optionA: 'DIM = miary liczbowe, FACT = atrybuty opisowe', optionB: 'FACT = miary liczbowe i klucze obce, DIM = atrybuty opisowe z kluczem głównym', optionC: 'Brak różnicy', optionD: 'DIM jest większy', correctOption: 'B', explanation: 'Tabela faktów przechowuje zdarzenia (miary + klucze), wymiary przechowują kontekst (kto, co, gdzie, kiedy).' },
    { text: 'Co to jest slowly changing dimension (SCD)?', optionA: 'Tabela z powolnymi zapytaniami', optionB: 'Technika śledzenia historii zmian atrybutów wymiaru w czasie', optionC: 'Indeks aktualizowany rzadko', optionD: 'Backup danych', correctOption: 'B', explanation: 'SCD (np. Type 2) śledzi historyczne wartości wymiarów — np. zmianę adresu klienta z zachowaniem historii.' },
    { text: 'Czym jest IQR (Interquartile Range)?', optionA: 'Różnicą między max a min', optionB: 'Różnicą między 75. a 25. percentylem (Q3 - Q1)', optionC: 'Odchyleniem standardowym', optionD: 'Średnią wartością', correctOption: 'B', explanation: 'IQR = Q3 - Q1. Używany do wykrywania outlierów: wartości poniżej Q1 - 1.5*IQR lub powyżej Q3 + 1.5*IQR.' },
    { text: 'Jakie zapytanie SQL znajdzie duplikaty w tabeli?', optionA: 'SELECT * FROM t WHERE id = id', optionB: 'SELECT kolumna, COUNT(*) FROM t GROUP BY kolumna HAVING COUNT(*) > 1', optionC: 'SELECT DISTINCT * FROM t', optionD: 'SELECT * FROM t ORDER BY kolumna', correctOption: 'B', explanation: 'GROUP BY + HAVING COUNT(*) > 1 identyfikuje wartości powtarzające się.' },
    { text: 'Co to jest data quality?', optionA: 'Szybkość zapytań', optionB: 'Stopień, w jakim dane są dokładne, kompletne, spójne, aktualne i unikalne', optionC: 'Format przechowywania', optionD: 'Rozmiar bazy danych', correctOption: 'B', explanation: 'Data quality = 6 wymiarów: accuracy, completeness, consistency, timeliness, uniqueness, validity.' },
    { text: 'Jak w pandas obliczyć korelację między kolumnami?', optionA: 'df.correlation()', optionB: 'df.corr()', optionC: 'df.cov()', optionD: 'df.pearson()', correctOption: 'B', explanation: 'df.corr() zwraca macierz korelacji Pearsona dla wszystkich par kolumn numerycznych.' },
    { text: 'Co to jest dashboard w kontekście analityki?', optionA: 'Interfejs administracyjny serwera', optionB: 'Wizualna prezentacja kluczowych wskaźników (KPI) w jednym miejscu', optionC: 'Procedura ETL', optionD: 'Tabela bazy danych', correctOption: 'B', explanation: 'Dashboard agreguje wizualizacje KPI, umożliwiając szybki przegląd stanu biznesu.' },
    { text: 'Czym jest feature engineering?', optionA: 'Projektowaniem architektury oprogramowania', optionB: 'Tworzeniem i transformowaniem zmiennych wejściowych dla modeli ML', optionC: 'Testowaniem modeli ML', optionD: 'Skalowaniem infrastruktury', correctOption: 'B', explanation: 'Feature engineering = tworzenie nowych cech lub transformacja istniejących, by poprawić wydajność modelu.' },
    { text: 'Jaki jest cel standaryzacji (z-score) danych?', optionA: 'Usunięcie braków danych', optionB: 'Przekształcenie danych do rozkładu o średniej 0 i std 1', optionC: 'Zakodowanie kategorii', optionD: 'Redukcja outlierów', correctOption: 'B', explanation: 'Z-score = (x - mean) / std. Standaryzacja ułatwia porównywanie zmiennych o różnych skalach.' },
    { text: 'Które SQL JOIN zwraca wiersze, które nie pasują do żadnego rekordu w drugiej tabeli?', optionA: 'INNER JOIN', optionB: 'CROSS JOIN', optionC: 'LEFT JOIN z WHERE prawa.id IS NULL', optionD: 'NATURAL JOIN', correctOption: 'C', explanation: 'Anti-join: LEFT JOIN + WHERE prawa.klucz IS NULL — zwraca wiersze z lewej bez odpowiedników w prawej.' },
    { text: 'Co to jest OLAP?', optionA: 'Online Application Processing', optionB: 'Online Analytical Processing — technologia wielowymiarowej analizy dużych zbiorów', optionC: 'Open Language for Analytics Programs', optionD: 'Object Linked Analysis Platform', correctOption: 'B', explanation: 'OLAP umożliwia wielowymiarową analizę (drill-down, roll-up, slice, dice) na hurtowni danych.' },
    { text: 'Jak pandas obsługuje brakujące daty w szeregach czasowych?', optionA: 'df.resample() z metodą forward fill (ffill)', optionB: 'df.dropna()', optionC: 'Automatycznie uzupełnia wartości', optionD: 'Zgłasza błąd', correctOption: 'A', explanation: 'resample() + ffill() / interpolate() pozwala wypełnić brakujące daty w szeregach czasowych.' },
    { text: 'Co to jest ROI (Return on Investment)?', optionA: '(Przychód - Koszt) / Koszt × 100%', optionB: 'Przychód / Liczba klientów', optionC: 'Koszt / Przychód × 100%', optionD: 'Zysk brutto / Liczba transakcji', correctOption: 'A', explanation: 'ROI = (Zysk - Inwestycja) / Inwestycja × 100%. Mierzy zwrot z inwestycji.' },
    { text: 'Która funkcja SQL usuwa wiodące i końcowe spacje?', optionA: 'CLEAN()', optionB: 'STRIP()', optionC: 'TRIM()', optionD: 'REPLACE()', correctOption: 'C', explanation: 'TRIM() usuwa spacje z początku i końca stringa. LTRIM/RTRIM — tylko z jednej strony.' },
    { text: 'Co to jest data lineage?', optionA: 'Historia zapytań do bazy', optionB: 'Śledzenie pochodzenia i transformacji danych od źródła do raportu', optionC: 'Schemat relacji między tabelami', optionD: 'Log błędów ETL', correctOption: 'B', explanation: 'Data lineage dokumentuje przepływ danych — skąd pochodzi każda kolumna i jakie transformacje przeszła.' },
    { text: 'Jaki jest cel walidacji danych w pipeline?', optionA: 'Przyspieszenie zapytań', optionB: 'Wykrycie i odrzucenie błędnych lub niekompletnych danych przed załadowaniem', optionC: 'Kompresja danych', optionD: 'Szyfrowanie danych', correctOption: 'B', explanation: 'Walidacja to bramka jakości: sprawdza typy, zakresy, unikalność przed załadowaniem do docelowego systemu.' },
    { text: 'Jak oblicza się Cohort Retention Rate?', optionA: 'Liczba nowych użytkowników / Całkowita liczba użytkowników', optionB: 'Użytkownicy aktywni w okresie N z danej kohorty / Użytkownicy w kohorcie przy starcie', optionC: 'Całkowity przychód / Liczba użytkowników', optionD: 'Liczba transakcji / Liczba użytkowników', correctOption: 'B', explanation: 'Retention Rate kohorty: ilu użytkowników z pierwotnej kohorty wróciło w danym okresie.' },
    { text: 'Co to jest percentyle w statystyce?', optionA: 'Wartości, które dzielą rozkład na 100 równych części', optionB: 'Procent wartości brakujących', optionC: 'Część ułamkowa liczby', optionD: 'Wynik normalizacji', correctOption: 'A', explanation: 'P50 = mediana, P95 = 95% wartości jest poniżej. Używane do monitorowania wydajności (latencja API).' },
    { text: 'Jaka jest różnica między precyzją (precision) a czułością (recall)?', optionA: 'Brak różnicy', optionB: 'Precision = TP/(TP+FP) — jak trafne są pozytywne predykcje; Recall = TP/(TP+FN) — ile prawdziwych pozytywnych wykryto', optionC: 'Precision dotyczy regresji, Recall klasyfikacji', optionD: 'Recall = 1 - Precision', correctOption: 'B', explanation: 'Precision: z predykowanych pozytywnych, ile było naprawdę pozytywnych. Recall: z rzeczywistych pozytywnych, ile wykryto.' },
    { text: 'Co robi EXPLAIN w SQL?', optionA: 'Dokumentuje zapytanie', optionB: 'Wyświetla plan wykonania zapytania bez jego uruchamiania', optionC: 'Sprawdza uprawnienia', optionD: 'Waliduje składnię', correctOption: 'B', explanation: 'EXPLAIN/EXPLAIN ANALYZE pokazuje plan wykonania — indeksy, joiny, koszty. Kluczowe do optymalizacji.' },
  ];

  for (const q of adQuestions) {
    await prisma.examQuestion.create({
      data: { courseId: analityka.id, ...q },
    });
  }
  console.log(`✅ Created ${adQuestions.length} questions for Analityka Danych`);

  // Pytania dla AI/ML (60 pytań — skrócona wersja, pierwsze 60)
  const aiQuestions = [
    { text: 'Co to jest uczenie maszynowe (Machine Learning)?', optionA: 'Programowanie robotów przemysłowych', optionB: 'Metoda nauki systemów na podstawie danych bez jawnego programowania reguł', optionC: 'Automatyczne tworzenie kodu', optionD: 'Symulacja fizyczna', correctOption: 'B', explanation: 'ML to dziedzina AI, gdzie modele uczą się wzorców z danych zamiast korzystać z hardkodowanych reguł.' },
    { text: 'Jaka jest różnica między uczeniem nadzorowanym a nienadzorowanym?', optionA: 'Nadzorowane jest szybsze', optionB: 'Nadzorowane używa etykietowanych danych; nienadzorowane odkrywa struktury bez etykiet', optionC: 'Nienadzorowane wymaga GPU', optionD: 'Brak różnicy w praktyce', correctOption: 'B', explanation: 'Supervised learning: mamy X i y (etykiety). Unsupervised: mamy tylko X, model odkrywa wzorce.' },
    { text: 'Co to jest overfitting?', optionA: 'Model zbyt dobrze dopasowany do danych treningowych, słabo generalizuje na nowe dane', optionB: 'Model z za małą liczbą parametrów', optionC: 'Błąd w danych treningowych', optionD: 'Zbyt długi czas trenowania', correctOption: 'A', explanation: 'Overfitting = model "zapamiętał" dane treningowe zamiast nauczyć się ogólnych wzorców.' },
    { text: 'Jaka technika zapobiega overfittingowi?', optionA: 'Zwiększenie liczby parametrów', optionB: 'Regularyzacja (L1/L2), dropout, więcej danych, walidacja krzyżowa', optionC: 'Zmniejszenie rozmiaru zbioru treningowego', optionD: 'Wyłączenie walidacji', correctOption: 'B', explanation: 'Regularyzacja dodaje karę za duże wagi. Dropout losowo wyłącza neurony. Walidacja krzyżowa wykrywa overfitting.' },
    { text: 'Co to jest gradient descent?', optionA: 'Algorytm sortowania', optionB: 'Metoda optymalizacji minimalizująca funkcję straty przez iteracyjne kroki w kierunku gradientu ujemnego', optionC: 'Technika redukcji wymiarów', optionD: 'Metoda oceny modelu', correctOption: 'B', explanation: 'Gradient descent aktualizuje parametry modelu w kierunku przeciwnym do gradientu funkcji straty.' },
    { text: 'Co to jest learning rate?', optionA: 'Czas trenowania modelu', optionB: 'Rozmiar kroku przy aktualizacji wag podczas gradient descent', optionC: 'Liczba epok trenowania', optionD: 'Rozmiar zbioru treningowego', correctOption: 'B', explanation: 'Zbyt duże LR → niestabilność; zbyt małe → wolna konwergencja. Typowe wartości: 0.001, 0.01.' },
    { text: 'Czym jest sieć neuronowa?', optionA: 'Algorytmem przeszukiwania grafu', optionB: 'Modelem obliczeniowym inspirowanym mózgiem, składającym się z warstw węzłów z wagami', optionC: 'Siecią komputerową do ML', optionD: 'Baza danych grafów', correctOption: 'B', explanation: 'Sieć neuronowa: warstwy (wejściowa, ukryte, wyjściowa) połączone wagami, z funkcjami aktywacji.' },
    { text: 'Co to jest CNN (Convolutional Neural Network)?', optionA: 'Sieć do przetwarzania tekstu', optionB: 'Sieć z warstwami splotu, zoptymalizowana do przetwarzania danych przestrzennych (obrazy)', optionC: 'Sieć rekurencyjna', optionD: 'Sieć generatywna', correctOption: 'B', explanation: 'CNN używa operacji splotu do wykrywania cech przestrzennych — idealna do klasyfikacji obrazów.' },
    { text: 'Do czego służy RNN?', optionA: 'Klasyfikacji obrazów', optionB: 'Przetwarzania danych sekwencyjnych (tekst, szeregi czasowe) z pamięcią kontekstu', optionC: 'Generowania obrazów', optionD: 'Redukcji wymiarów', correctOption: 'B', explanation: 'RNN przetwarza sekwencje, zachowując ukryty stan (pamięć) — ale ma problem znikającego gradientu.' },
    { text: 'Czym jest Transformer?', optionA: 'Konwerterem napięcia', optionB: 'Architekturą sieci neuronowej z mechanizmem attention, podstawą modeli LLM', optionC: 'Algorytmem etl', optionD: 'Typem regularyzacji', correctOption: 'B', explanation: 'Transformer (2017) = attention + feed-forward. Podstawa GPT, BERT, LLaMA — zastąpił RNN w NLP.' },
    { text: 'Co oznacza accuracy (dokładność) modelu klasyfikacji?', optionA: 'Czas predykcji', optionB: 'Odsetek poprawnie sklasyfikowanych próbek: (TP+TN) / (TP+TN+FP+FN)', optionC: 'Liczba warstw modelu', optionD: 'Rozmiar modelu w MB', correctOption: 'B', explanation: 'Accuracy = procent poprawnych predykcji. Może być myląca przy niezbalansowanych klasach.' },
    { text: 'Co to jest F1 Score?', optionA: 'Pierwszy wynik modelu', optionB: 'Harmonic mean precyzji i czułości: 2 × (Precision × Recall) / (Precision + Recall)', optionC: 'Dokładność na zbiorze testowym', optionD: 'Liczba epok do konwergencji', correctOption: 'B', explanation: 'F1 balansuje Precision i Recall — lepszy niż accuracy dla niezbalansowanych klas.' },
    { text: 'Co to jest cross-validation?', optionA: 'Trening na wielu GPU', optionB: 'Technika oceny modelu przez wielokrotny podział danych na folds treningowe/walidacyjne', optionC: 'Łączenie wielu modeli', optionD: 'Regularyzacja modelu', correctOption: 'B', explanation: 'K-fold CV: dane dzielone na k części, model trenowany k razy — każdy fold raz jako walidacja.' },
    { text: 'Jaki algorytm używa "drzew decyzyjnych" i losowania?', optionA: 'SVM', optionB: 'Random Forest', optionC: 'K-Means', optionD: 'PCA', correctOption: 'B', explanation: 'Random Forest = ensemble wielu drzew decyzyjnych trenowanych na losowych podzbiorach danych i cech.' },
    { text: 'Co to jest PCA (Principal Component Analysis)?', optionA: 'Algorytm klastrowania', optionB: 'Technika redukcji wymiarów poprzez znalezienie kierunków maksymalnej wariancji', optionC: 'Metoda klasyfikacji', optionD: 'Algorytm optymalizacji', correctOption: 'B', explanation: 'PCA transformuje dane do nowego układu współrzędnych — pierwsze komponenty wyjaśniają największą wariancję.' },
    { text: 'Co to jest K-Means?', optionA: 'Algorytm klasyfikacji', optionB: 'Algorytm klasteryzacji grupujący dane w k skupień minimalizując inercję', optionC: 'Metoda regresji', optionD: 'Technika augmentacji danych', correctOption: 'B', explanation: 'K-Means iteracyjnie przypisuje punkty do k centroidów i aktualizuje centroidy — uczenie nienadzorowane.' },
    { text: 'Czym jest batch size w uczeniu głębokim?', optionA: 'Liczbą warstw sieci', optionB: 'Liczbą próbek używanych do jednej aktualizacji wag', optionC: 'Rozmiarem modelu', optionD: 'Czasem jednej epoki', correctOption: 'B', explanation: 'Batch size: mini-batch SGD (32, 64, 128) to kompromis między stabilnością a prędkością trenowania.' },
    { text: 'Co to jest epoch w kontekście trenowania modelu?', optionA: 'Jeden krok gradient descent', optionB: 'Jedno przejście przez cały zbiór treningowy', optionC: 'Jedna warstwa sieci neuronowej', optionD: 'Jeden test modelu', correctOption: 'B', explanation: 'Epocha = model zobaczył każdy przykład treningowy dokładnie raz. Trenowanie trwa zazwyczaj wiele epok.' },
    { text: 'Co robi funkcja aktywacji ReLU?', optionA: 'Zwraca sigmoid: 1/(1+e^-x)', optionB: 'Zwraca max(0, x) — zeruje wartości ujemne', optionC: 'Normalizuje dane wejściowe', optionD: 'Oblicza softmax', correctOption: 'B', explanation: 'ReLU = Rectified Linear Unit: f(x) = max(0, x). Prosta, szybka, ale może "umierać" dla x < 0.' },
    { text: 'Co to jest transfer learning?', optionA: 'Przenoszenie modelu między serwerami', optionB: 'Wykorzystanie wiedzy z pre-trenowanego modelu jako punktu startowego dla nowego zadania', optionC: 'Eksport wag modelu', optionD: 'Trenowanie na wielu maszynach', correctOption: 'B', explanation: 'Transfer learning: fine-tuning BERT/GPT/ResNet dla własnego zadania zamiast trenowania od zera.' },
    { text: 'Czym jest embedding w NLP?', optionA: 'Szyfrowaniem tekstu', optionB: 'Reprezentacją tokenów/słów jako wektorów liczb rzeczywistych w przestrzeni latentnej', optionC: 'Kompresją tekstu', optionD: 'Lematyzacją tekstu', correctOption: 'B', explanation: 'Word embeddings (Word2Vec, GloVe, BERT) mapują słowa do gęstych wektorów zachowujących semantykę.' },
    { text: 'Co to jest attention mechanism?', optionA: 'Mechanizm skupiania na ważnych fragmentach sekwencji wejściowej', optionB: 'Algorytm pruning sieci', optionC: 'Technika regularyzacji', optionD: 'Funkcja straty', correctOption: 'A', explanation: 'Attention pozwala modelowi "skupić się" na różnych częściach wejścia przy generowaniu każdego tokenu wyjścia.' },
    { text: 'Jaka biblioteka Python jest popularna do głębokiego uczenia?', optionA: 'scikit-learn', optionB: 'pandas', optionC: 'PyTorch', optionD: 'matplotlib', correctOption: 'C', explanation: 'PyTorch (Meta) i TensorFlow/Keras (Google) to główne frameworki do deep learning. scikit-learn = klasyczny ML.' },
    { text: 'Co to jest hyperparameter tuning?', optionA: 'Zmiana architektury sieci po trenowaniu', optionB: 'Optymalizacja parametrów konfiguracyjnych modelu (LR, batch size, architektura)', optionC: 'Aktualizacja wag podczas trenowania', optionD: 'Walidacja modelu', correctOption: 'B', explanation: 'Hyperparametry nie są uczone — ustawiane przed treningiem. Grid search, Random search, Bayesian optimization.' },
    { text: 'Co to jest confusion matrix?', optionA: 'Macierz korelacji zmiennych', optionB: 'Tabela TP/FP/TN/FN pokazująca rozkład predykcji modelu klasyfikacji', optionC: 'Macierz wag sieci neuronowej', optionD: 'Wizualizacja funkcji straty', correctOption: 'B', explanation: 'Confusion matrix: wiersze = rzeczywiste klasy, kolumny = predykowane. TP, FP, FN, TN na przekątnej.' },
    { text: 'Czym jest ROC AUC?', optionA: 'Funkcją straty', optionB: 'Polem pod krzywą ROC (TPR vs FPR) — mierzy zdolność modelu do rozróżniania klas (1.0 = ideał)', optionC: 'Metodą regularyzacji', optionD: 'Algorytmem klasteryzacji', correctOption: 'B', explanation: 'AUC = Area Under ROC Curve. 0.5 = losowy, 1.0 = idealny. Niezależny od progu decyzyjnego.' },
    { text: 'Co to jest SVM (Support Vector Machine)?', optionA: 'Typ sieci neuronowej', optionB: 'Algorytm klasyfikacji/regresji znajdując hiperpłaszczyznę maksymalizującą margines między klasami', optionC: 'Metoda klasteryzacji', optionD: 'Algorytm ETL', correctOption: 'B', explanation: 'SVM: wyznacza hyperpłaszczyznę z maksymalnym marginesem. Kernel trick pozwala na nieliniowe granice.' },
    { text: 'Czym jest data augmentation?', optionA: 'Oczyszczaniem danych', optionB: 'Sztucznym powiększaniem zbioru treningowego przez transformacje istniejących próbek', optionC: 'Zbieraniem nowych danych', optionD: 'Kompresją datasetu', correctOption: 'B', explanation: 'Augmentacja dla obrazów: obroty, skalowanie, flip. Dla tekstu: parafrazowanie, back-translation.' },
    { text: 'Co to jest dropout w sieciach neuronowych?', optionA: 'Usuwanie epok trenowania', optionB: 'Technika regularyzacji losowo zerująca aktywacje neuronów podczas trenowania', optionC: 'Zmniejszanie LR', optionD: 'Usuwanie słabych modeli w ensemble', correctOption: 'B', explanation: 'Dropout (p=0.5) losowo zeruje % neuronów w każdym kroku trenowania — model uczy się bardziej robustnych cech.' },
    { text: 'Jaka funkcja straty jest typowa dla klasyfikacji wieloklasowej?', optionA: 'MSE (Mean Squared Error)', optionB: 'Cross-Entropy Loss', optionC: 'Hinge Loss', optionD: 'MAE (Mean Absolute Error)', correctOption: 'B', explanation: 'Cross-entropy = -Σ y_true × log(y_pred). Dla binarnej: Binary CE. Dla wieloklasowej: Categorical CE.' },
    { text: 'Co to jest generative AI?', optionA: 'AI do klasyfikacji', optionB: 'Systemy AI zdolne do tworzenia nowych treści (tekst, obrazy, dźwięk, kod)', optionC: 'AI do wykrywania anomalii', optionD: 'AI do rekomendacji', correctOption: 'B', explanation: 'Generative AI (GPT, Stable Diffusion, MusicGen) tworzy nowe treści na podstawie wzorców z danych treningowych.' },
    { text: 'Czym jest LLM (Large Language Model)?', optionA: 'Modelem logistycznej regresji', optionB: 'Dużym modelem językowym trenowanym na ogromnych korpusach tekstu do generowania i rozumienia języka', optionC: 'Algorytmem klasteryzacji tekstu', optionD: 'Narzędziem do analizy sentymentu', correctOption: 'B', explanation: 'LLM (GPT-4, LLaMA, Claude) = bardzo duże Transformery trenowane na setkach miliardów tokenów tekstu.' },
    { text: 'Co to jest RAG (Retrieval-Augmented Generation)?', optionA: 'Technika trenowania modeli', optionB: 'Architektura łącząca retrieval (wyszukiwanie dokumentów) z generacją LLM dla aktualnych odpowiedzi', optionC: 'Metoda fine-tuningu', optionD: 'Algorytm kompresji modelu', correctOption: 'B', explanation: 'RAG: (1) wyszukaj relevantne dokumenty z bazy wiedzy, (2) podaj jako kontekst do LLM. Aktualna wiedza bez fine-tuningu.' },
    { text: 'Co to jest vector database?', optionA: 'Baza danych wektorów fizycznych', optionB: 'Baza zoptymalizowana do przechowywania i wyszukiwania podobieństwa embeddingów (ANN search)', optionC: 'Baza danych grafów', optionD: 'Relacyjna baza danych', correctOption: 'B', explanation: 'Vector DB (Pinecone, Weaviate, pgvector): ANN search dla embeddingów. Kluczowa w RAG i semantic search.' },
    { text: 'Co to jest fine-tuning modelu językowego?', optionA: 'Trenowanie od zera', optionB: 'Dalsze trenowanie pre-trenowanego modelu na specyficznym zbiorze danych lub zadaniu', optionC: 'Kompresja modelu', optionD: 'Walidacja modelu', correctOption: 'B', explanation: 'Fine-tuning dostosowuje ogólny model (GPT, LLaMA) do konkretnego domenowego zadania przy mniejszym zbiorze danych.' },
    { text: 'Czym jest prompt engineering?', optionA: 'Programowaniem chatbotów', optionB: 'Projektowaniem skutecznych instrukcji wejściowych dla modeli LLM', optionC: 'Tworzeniem baz danych promptów', optionD: 'Optymalizacją kodu modelu', correctOption: 'B', explanation: 'Prompt engineering: few-shot, chain-of-thought, system prompt — techniki poprawiające jakość odpowiedzi LLM.' },
    { text: 'Co to jest hallucination w kontekście LLM?', optionA: 'Wizualizacja danych', optionB: 'Generowanie przez model fałszywych, ale brzmiących przekonująco informacji', optionC: 'Błąd w kodzie modelu', optionD: 'Odpowiedź poza zakresem tematycznym', correctOption: 'B', explanation: 'Halucynacja = model generuje pewnym tonem fakty, które nie istnieją. Główne ryzyko LLM w produkcji.' },
    { text: 'Jakie miary używamy do ewaluacji modeli generatywnych tekstu?', optionA: 'Accuracy i F1', optionB: 'BLEU, ROUGE, perplexity', optionC: 'MSE i MAE', optionD: 'ROC AUC', correctOption: 'B', explanation: 'BLEU/ROUGE mierzą n-gram overlap między generacją a referencją. Perplexity mierzy pewność modelu językowego.' },
    { text: 'Co to jest model distillation?', optionA: 'Trening na surowych danych', optionB: 'Trenowanie małego modelu (student) by naśladował duży model (teacher)', optionC: 'Dekodowanie modelu', optionD: 'Augmentacja danych', correctOption: 'B', explanation: 'Knowledge distillation: mały student model uczy się z soft labels dużego teacher, osiągając podobną jakość.' },
    { text: 'Co to jest RLHF?', optionA: 'Reinforcement Learning from Human Feedback — fine-tuning przez nagrody od ludzkiej oceny', optionB: 'Rapid Learning for High Frequency', optionC: 'Regularized Linear High Function', optionD: 'Recursive Layer Hierarchy Feature', correctOption: 'A', explanation: 'RLHF (ChatGPT, Claude) używa ludzkich preferencji do trenowania reward model i optymalizacji polityki LLM.' },
    { text: 'Jaką bibliotekę Python używa się do obliczeń na tensorach z obsługą GPU?', optionA: 'pandas', optionB: 'NumPy', optionC: 'PyTorch / TensorFlow', optionD: 'scikit-learn', correctOption: 'C', explanation: 'PyTorch (torch.Tensor) i TensorFlow obsługują CUDA GPU. NumPy działa tylko na CPU.' },
    { text: 'Co to jest semantic search?', optionA: 'Wyszukiwanie słów kluczowych', optionB: 'Wyszukiwanie rozumiejące znaczenie i kontekst zapytania, a nie dosłowne słowa', optionC: 'Wyszukiwanie w kodzie źródłowym', optionD: 'Wyszukiwanie gramatyczne', correctOption: 'B', explanation: 'Semantic search używa embeddingów — zapytanie i dokumenty w tej samej przestrzeni wektorowej (cosine similarity).' },
    { text: 'Czym jest model deployment?', optionA: 'Trenowaniem modelu', optionB: 'Procesem udostępniania wytrenowanego modelu jako serwisu (API) do produkcyjnego użytku', optionC: 'Walidacją modelu', optionD: 'Archiwizacją modelu', correctOption: 'B', explanation: 'Model deployment: serializacja (ONNX, TorchScript), konteneryzacja (Docker), serwowanie (FastAPI, Triton).' },
    { text: 'Co to jest model drift?', optionA: 'Aktualizacja modelu', optionB: 'Degradacja wydajności modelu w czasie gdy dane produkcyjne odchylają się od danych treningowych', optionC: 'Migracja modelu do nowego serwera', optionD: 'Kompresja modelu', correctOption: 'B', explanation: 'Data/concept drift: rozkład danych produkcyjnych zmienia się → model traci jakość. Wymaga monitoringu i retreningu.' },
    { text: 'Co to jest feature importance w Random Forest?', optionA: 'Liczba cech modelu', optionB: 'Miara jak bardzo dana cecha przyczynia się do decyzji modelu (np. mean decrease impurity)', optionC: 'Czas obliczenia cech', optionD: 'Korelacja cech', correctOption: 'B', explanation: 'Feature importance w RF mierzy średnie zmniejszenie nieczystości Giniego przez daną cechę w drzewach.' },
    { text: 'Czym jest LIME/SHAP?', optionA: 'Bibliotekami do wizualizacji', optionB: 'Technikami wyjaśnialności modeli ML (XAI) — wyjaśniają lokalne i globalne predykcje', optionC: 'Algorytmami klasteryzacji', optionD: 'Formatami serializacji modeli', correctOption: 'B', explanation: 'SHAP (Shapley values) i LIME wyjaśniają co model "myśli" przy konkretnej predykcji — kluczowe dla regulacji AI.' },
    { text: 'Co to jest MLOps?', optionA: 'Oprogramowanie do zarządzania ML', optionB: 'Praktyki i narzędzia automatyzujące cykl życia modeli ML (trening, deployment, monitoring, retraining)', optionC: 'Protokół komunikacji między modelami', optionD: 'Typ modelu ML', correctOption: 'B', explanation: 'MLOps = DevOps dla ML: ML pipeline, model registry, CI/CD dla modeli, monitoring driftu.' },
    { text: 'Jaka jest różnica między AI a ML?', optionA: 'AI to podzbiór ML', optionB: 'ML to podzbiór AI — AI obejmuje wszystkie techniki symulujące inteligencję, ML to uczenie z danych', optionC: 'Są identyczne', optionD: 'ML działa bez danych', correctOption: 'B', explanation: 'AI (szeroka dziedzina) ⊃ ML (uczenie z danych) ⊃ DL (głębokie sieci neuronowe).' },
    { text: 'Co to jest zero-shot learning?', optionA: 'Trenowanie modelu bez danych', optionB: 'Zdolność modelu do wykonania zadania bez przykładów treningowych dla tej klasy/zadania', optionC: 'Trenowanie bez GPU', optionD: 'Walidacja bez zbioru testowego', correctOption: 'B', explanation: 'Zero-shot: LLM wykonuje nowe zadanie tylko na podstawie opisu. GPT-4 klasyfikuje nowe klasy bez przykładów.' },
    { text: 'Czym jest cosine similarity?', optionA: 'Miarą kąta między wektorami (0-1, 1=identyczne kierunki)', optionB: 'Odległością euklidesową', optionC: 'Miarą długości wektora', optionD: 'Korelacją Spearmana', correctOption: 'A', explanation: 'Cosine similarity: cos(θ) = (A·B)/(||A||·||B||). Używana do podobieństwa embeddingów niezależnie od długości wektora.' },
    { text: 'Co to jest model quantization?', optionA: 'Zwiększaniem precyzji modelu', optionB: 'Redukcją precyzji wag (np. float32 → int8) dla zmniejszenia rozmiary i przyspieszenia inferencji', optionC: 'Skalowaniem danych wejściowych', optionD: 'Dodawaniem warstw do modelu', correctOption: 'B', explanation: 'Quantization (8-bit, 4-bit) zmniejsza rozmiar modelu 4-8x kosztem niewielkiej utraty jakości — kluczowe dla LLM na edge.' },
    { text: 'Co to jest Responsible AI?', optionA: 'AI z lepszymi wynikami', optionB: 'Praktyki zapewniające, że systemy AI są sprawiedliwe, transparentne, bezpieczne i etyczne', optionC: 'AI bez błędów', optionD: 'Szybka AI', correctOption: 'B', explanation: 'Responsible AI: fairness (brak biasów), explainability, privacy, safety, accountability — wymagane przez regulacje (AI Act UE).' },
    { text: 'Czym jest EU AI Act?', optionA: 'Prawem o rejestracji firm AI', optionB: 'Regulacją UE klasyfikującą systemy AI według ryzyka i nakładającą obowiązki na high-risk AI', optionC: 'Normą ISO dla AI', optionD: 'Protokołem API', correctOption: 'B', explanation: 'EU AI Act (2024): unacceptable risk (ban) / high risk (transparencja, audyt) / limited risk / minimal risk.' },
    { text: 'Co to jest token w LLM?', optionA: 'Hasłem użytkownika', optionB: 'Jednostką tekstu (słowo, część słowa lub znak) na której operuje model językowy', optionC: 'Kluczem API', optionD: 'Parametrem modelu', correctOption: 'B', explanation: 'Tokenizacja (BPE, WordPiece): "sztuczna inteligencja" → ["szt", "uczna", " intel", "igencja"]. 1 token ≈ 0.75 słowa.' },
    { text: 'Jaka jest różnica między parametrami a hiperparametrami modelu?', optionA: 'Brak różnicy', optionB: 'Parametry są uczone z danych (wagi); hiperparametry są ustawiane przed treningiem (LR, batch size)', optionC: 'Parametry to dane wejściowe', optionD: 'Hiperparametry to błędy walidacji', correctOption: 'B', explanation: 'Parametry = wagi/biasy uczone przez SGD. Hiperparametry = konfiguracja modelu ustawiana przez programistę.' },
    { text: 'Co to jest ensemble learning?', optionA: 'Trenowanie modelu na wielu GPU', optionB: 'Kombinowanie predykcji wielu modeli (bagging, boosting, stacking) dla lepszych wyników', optionC: 'Trenowanie na wielu datasetach', optionD: 'Synchronizacja wag modeli', correctOption: 'B', explanation: 'Ensemble: Random Forest (bagging), XGBoost (boosting), Stacking. Zwykle lepsze niż pojedynczy model.' },
    { text: 'Co to jest context window LLM?', optionA: 'Oknem interfejsu aplikacji', optionB: 'Maksymalną liczbą tokenów jaką model może przetworzyć naraz (input + output)', optionC: 'Rozmiarem bazy wektorowej', optionD: 'Pamięcią podręczną GPU', correctOption: 'B', explanation: 'Context window: 8K (GPT-3.5), 128K (GPT-4o), 200K (Claude 3). Ogranicza ile tekstu model "widzi" naraz.' },
    { text: 'Co to jest AI bias?', optionA: 'Błąd w kodzie AI', optionB: 'Systematyczna niesprawiedliwość w predykcjach AI wynikająca z biasów w danych lub algorytmie', optionC: 'Parametr w sieci neuronowej', optionD: 'Wolna inferencja modelu', correctOption: 'B', explanation: 'AI bias: model może dyskryminować grupy (gender, rasa) jeśli dane treningowe zawierają historyczne uprzedzenia.' },
    { text: 'Czym jest mean squared error (MSE)?', optionA: 'Miarą dokładności klasyfikacji', optionB: 'Średnią kwadratów różnic między predykcją a rzeczywistą wartością', optionC: 'Funkcją straty dla sieci generatywnych', optionD: 'Odchyleniem standardowym', correctOption: 'B', explanation: 'MSE = (1/n) × Σ(y_pred - y_true)². Używany w regresji. Silnie karze duże błędy (przez kwadrat).' },
    { text: 'Co to jest knowledge graph?', optionA: 'Wykresem wiedzy menedżerskiej', optionB: 'Grafem reprezentującym encje i relacje między nimi, używanym do wzbogacania AI o ustrukturyzowaną wiedzę', optionC: 'Wizualizacją sieci neuronowej', optionD: 'Diagramem przepływu danych', correctOption: 'B', explanation: 'Knowledge graph (trójki podmiot-relacja-obiekt): "Polska → stolica → Warszawa". Używany przez Google, RAG, systemy QA.' },
  ];

  for (const q of aiQuestions) {
    await prisma.examQuestion.create({
      data: { courseId: ai.id, ...q },
    });
  }
  console.log(`✅ Created ${aiQuestions.length} questions for AI/ML`);

  console.log('🎉 Seeding complete!');
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => { console.error(e); prisma.$disconnect(); process.exit(1); });
