import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          navy: '#1B2E4B',
          gold: '#C9A94B',
          teal: '#00A896',
          gray: '#F8F9FA',
          dark: '#1A1A2E',
          muted: '#64748B',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': '#1A1A2E',
            '--tw-prose-headings': '#1B2E4B',
            '--tw-prose-links': '#00A896',
            '--tw-prose-bold': '#1B2E4B',
            '--tw-prose-counters': '#64748B',
            '--tw-prose-bullets': '#64748B',
            '--tw-prose-hr': '#e5e7eb',
            '--tw-prose-quotes': '#1B2E4B',
            '--tw-prose-quote-borders': '#00A896',
            '--tw-prose-captions': '#64748B',
            '--tw-prose-code': '#1B2E4B',
            '--tw-prose-pre-code': '#e2e8f0',
            '--tw-prose-pre-bg': '#0d1117',
            '--tw-prose-th-borders': '#d1d5db',
            '--tw-prose-td-borders': '#e5e7eb',
            maxWidth: 'none',
            a: { color: '#00A896', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
            h1: { fontFamily: 'var(--font-plus-jakarta)', fontWeight: '700', color: '#1B2E4B' },
            h2: { fontFamily: 'var(--font-plus-jakarta)', fontWeight: '700', color: '#1B2E4B', marginTop: '2.5rem', marginBottom: '1rem', paddingBottom: '0.5rem', borderBottom: '1px solid #e5e7eb' },
            h3: { fontFamily: 'var(--font-plus-jakarta)', fontWeight: '600', color: '#1B2E4B', marginTop: '2rem', marginBottom: '0.75rem' },
            h4: { fontFamily: 'var(--font-plus-jakarta)', fontWeight: '600', color: '#1B2E4B' },
            pre: {
              backgroundColor: '#0d1117',
              color: '#e2e8f0',
              borderRadius: '0.5rem',
              padding: '1.25rem 1.5rem',
              overflowX: 'auto',
              maxWidth: '100%',
              fontSize: '0.875rem',
              lineHeight: '1.7',
              fontFamily: 'var(--font-jetbrains-mono), monospace',
              border: '1px solid #30363d',
              WebkitOverflowScrolling: 'touch',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              fontSize: 'inherit',
              fontFamily: 'inherit',
              padding: '0',
              borderRadius: '0',
              whiteSpace: 'pre',
              wordBreak: 'normal',
              overflowWrap: 'normal',
            },
            code: {
              backgroundColor: '#f1f5f9',
              color: '#1B2E4B',
              padding: '0.125rem 0.375rem',
              borderRadius: '0.25rem',
              fontSize: '0.875em',
              fontFamily: 'var(--font-jetbrains-mono), monospace',
              fontWeight: '400',
              '&::before': { content: '""' },
              '&::after': { content: '""' },
            },
            table: {
              fontSize: '0.875rem',
              width: '100%',
              borderCollapse: 'collapse',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
            },
            thead: { borderBottomWidth: '2px', borderBottomColor: '#d1d5db' },
            'thead th': {
              backgroundColor: '#F8F9FA',
              color: '#1B2E4B',
              fontWeight: '600',
              padding: '0.75rem 1rem',
              textAlign: 'left',
              borderBottom: '2px solid #d1d5db',
            },
            'tbody tr': { borderBottomWidth: '1px', borderBottomColor: '#e5e7eb' },
            'tbody tr:last-child': { borderBottomWidth: '0' },
            'tbody tr:nth-child(even)': { backgroundColor: '#fafafa' },
            'tbody td': { padding: '0.75rem 1rem', verticalAlign: 'top' },
            blockquote: {
              borderLeftWidth: '4px',
              borderLeftColor: '#00A896',
              backgroundColor: '#f0fdfb',
              padding: '1rem 1.25rem',
              borderRadius: '0 0.5rem 0.5rem 0',
              fontStyle: 'normal',
              color: '#1A1A2E',
              'p:first-of-type::before': { content: '""' },
              'p:last-of-type::after': { content: '""' },
            },
            hr: { borderColor: '#e5e7eb', marginTop: '2.5rem', marginBottom: '2.5rem' },
            strong: { color: '#1B2E4B', fontWeight: '600' },
            p: { lineHeight: '1.85', marginTop: '0', marginBottom: '1.5rem' },
            li: { marginTop: '0.375rem', marginBottom: '0.375rem', lineHeight: '1.75' },
            'ul > li::marker': { color: '#00A896' },
            'ol > li::marker': { color: '#64748B' },
            'ul, ol': { paddingLeft: '1.5rem', marginTop: '0.5rem', marginBottom: '1.25rem' },
            'ul ul, ol ol, ul ol, ol ul': { marginTop: '0.25rem', marginBottom: '0.25rem' },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};

export default config;
